import { IUser } from '@/types';

export const mockUsers: IUser[] = [
  {
    uid: 'user-1',
    civility: 'Mr.',
    first_name: 'John',
    last_name: 'Doe',
    phone_number: '+1234567890',
    email: 'john.doe@example.com',
    hashed_password: '$2b$10$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', // Example hashed password
    is_admin: false,
    job_title: 'Software Engineer',
    job_department: 'Engineering',
    remaining_leave_balance: 20,
    hire_date: '2023-01-15',
    created_at: '2023-01-10',
    updated_at: '2023-01-15',
    departure_date: undefined,
    is_archived: false,
    reset_code: undefined,
    address_line1: '123 Main St',
    address_line2: 'Apt 2B',
    city: 'Anytown',
    postal_code: '12345',
    country: 'USA',
    date_of_birth: '1990-01-15',
    social_security_number: 'XXX-XX-XXXX', // Example SSN
    marital_status: 'Married',
    contract_type: 'Full-time',
    dependants: 2,
    company_id: 'company-abc',
  },
  {
    uid: 'user-2',
    civility: 'Ms.',
    first_name: 'Jane',
    last_name: 'Smith',
    phone_number: '+9876543210',
    email: 'jane.smith@example.com',
    hashed_password: '$2b$10$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', // Example hashed password
    is_admin: false,
    job_title: 'Marketing Manager',
    job_department: 'Marketing',
    remaining_leave_balance: 15,
    hire_date: '2022-05-20',
    created_at: '2022-05-15',
    updated_at: '2022-05-20',
    departure_date: undefined,
    is_archived: false,
    reset_code: undefined,
    address_line1: '456 Elm St',
    city: 'Othertown',
    postal_code: '54321',
    country: 'USA',
    date_of_birth: '1985-07-04',
    social_security_number: 'YYY-YY-YYYY', // Example SSN
    marital_status: 'Single',
    contract_type: 'Full-time',
    dependants: 0,
    company_id: 'company-abc',
  },
  {
    uid: 'user-3',
    civility: 'Mr.',
    first_name: 'David',
    last_name: 'Lee',
    phone_number: '+5551234567',
    email: 'david.lee@example.com',
    hashed_password: '$2b$10$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', // Example hashed password
    is_admin: true,
    job_title: 'CEO',
    job_department: 'Executive',
    remaining_leave_balance: 30,
    hire_date: '2020-01-01',
    created_at: '2020-01-01',
    updated_at: '2020-01-01',
    departure_date: undefined,
    is_archived: false,
    reset_code: undefined,
    address_line1: '789 Oak Ave',
    city: 'Newtown',
    postal_code: '67890',
    country: 'USA',
    date_of_birth: '1975-12-25',
    social_security_number: 'ZZZ-ZZ-ZZZZ', // Example SSN
    marital_status: 'Married',
    contract_type: 'Full-time',
    dependants: 3,
    company_id: 'company-abc',
  },
  {
    uid: 'user-4',
    civility: 'Ms.',
    first_name: 'Sarah',
    last_name: 'Jones',
    phone_number: '+1112223333',
    email: 'sarah.jones@example.com',
    hashed_password: '$2b$10$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', // Example hashed password
    is_admin: false,
    job_title: 'HR Manager',
    job_department: 'Human Resources',
    remaining_leave_balance: 18,
    hire_date: '2021-08-10',
    created_at: '2021-08-05',
    updated_at: '2021-08-10',
    departure_date: undefined,
    is_archived: false,
    reset_code: undefined,
    address_line1: '101 Pine St',
    city: 'Townville',
    postal_code: '98765',
    country: 'USA',
    date_of_birth: '1988-03-12',
    social_security_number: 'AAA-AA-AAAA', // Example SSN
    marital_status: 'Single',
    contract_type: 'Full-time',
    dependants: 1,
    company_id: 'company-abc',
  },
  {
    uid: 'user-5',
    civility: 'Mr.',
    first_name: 'Michael',
    last_name: 'Brown',
    phone_number: '+4445556666',
    email: 'michael.brown@example.com',
    hashed_password: '$2b$10$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', // Example hashed password
    is_admin: false,
    job_title: 'Software Engineer',
    job_department: 'Engineering',
    remaining_leave_balance: 22,
    hire_date: '2023-03-20',
    created_at: '2023-03-15',
    updated_at: '2023-03-20',
    departure_date: undefined,
    is_archived: false,
    reset_code: undefined,
    address_line1: '202 Maple Ave',
    city: 'Villagetown',
    postal_code: '54321',
    country: 'USA',
    date_of_birth: '1992-11-05',
    social_security_number: 'BBB-BB-BBBB', // Example SSN
    marital_status: 'Married',
    contract_type: 'Full-time',
    dependants: 0,
    company_id: 'company-abc',
  },
  {
    uid: 'user-6',
    civility: 'Ms.',
    first_name: 'Emily',
    last_name: 'Davis',
    phone_number: '+7778889999',
    email: 'emily.davis@example.com',
    hashed_password: '$2b$10$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', // Example hashed password
    is_admin: false,
    job_title: 'Marketing Specialist',
    job_department: 'Marketing',
    remaining_leave_balance: 17,
    hire_date: '2022-11-10',
    created_at: '2022-11-05',
    updated_at: '2022-11-10',
    departure_date: undefined,
    is_archived: false,
    reset_code: undefined,
    address_line1: '303 Cherry Lane',
    city: 'Hometown',
    postal_code: '12345',
    country: 'USA',
    date_of_birth: '1987-02-18',
    social_security_number: 'CCC-CC-CCCC', // Example SSN
    marital_status: 'Single',
    contract_type: 'Full-time',
    dependants: 0,
    company_id: 'company-abc',
  },
];
